name: Skullcrates
version: ${project.version}
main: de.skyenton.skullcrates.SkullcratesPlugin
authors: [ SkyEnton, MorrisBr, H565656 ]
description: Crate System für diverse Server von SkyEnton
website: SkyEnton.de

commands:
  crate: